# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arcton
email: team@arcton.nz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arcton.nz" # the base hostname & protocol for your site
collections:
  projects:
    display: "Projects"
    icon: "folder-open"
    output: true
    menu_order: 10
  competitions:
    display: "Competitions"
    icon: "trophy"
    output: true
    menu_order: 20
  ace:
    display: "ACE"
    icon: "code"
    output: true
    menu_order: 30

# Build settings
markdown: kramdown
